---
title: "Persönliche Vorhersage"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Sie sind auf die Zuneigung und Bewunderung anderer angewiesen, neigen aber dennoch zu Selbstkritik. Ihre Persönlichkeit weist einige Schwächen auf, die Sie aber im Allgemeinen ausgleichen können. Beträchtliche Fähigkeiten lassen Sie brachliegen, statt sie zu Ihrem Vorteil zu nutzen. Äußerlich diszipliniert und selbstbeherrscht, neigen Sie dazu, sich innerlich ängstlich und unsicher zu fühlen. Mitunter zweifeln Sie stark an der Richtigkeit Ihres Tuns und Ihrer Entscheidungen. Sie bevorzugen ein gewisses Maß an Abwechslung und Veränderung und sind unzufrieden, wenn Sie von Verboten und Beschränkungen eingeengt werden. Sie sind stolz auf Ihr unabhängiges Denken und nehmen anderer Leute Aussagen nicht unbewiesen hin. Doch finden Sie es unklug, sich anderen allzu bereitwillig zu öffnen. Manchmal verhalten Sie sich extrovertiert, leutselig und aufgeschlossen, dann aber auch wieder introvertiert, skeptisch und zurückhaltend. Manche Ihrer Hoffnungen sind ziemlich unrealistisch.

Bitte bewerten Sie nun hier, inwieweit diese Vorhersage auf Sie zutrifft.

<iframe src="https://app.sli.do/event/aa6boBn7Jp3HsB6C1bu6qJ/embed/polls/aba8125a-7928-4841-9efa-930591f965b5" width="300" height="400"></iframe>

Falls die Umfrage hier nicht angezeigt wird, folgen Sie bitte diesem Link: 
<a href="https://app.sli.do/event/aa6boBn7Jp3HsB6C1bu6qJ/embed/polls/aba8125a-7928-4841-9efa-930591f965b5">Zur Umfrage</a>
